// Code generated by dagger-compiler.  Do not edit.
package com.aaron.smarttravel.main;

import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<HomeActivity>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code HomeActivity} and its
 * dependencies.
 *
 * Being a {@code Provider<HomeActivity>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<HomeActivity>} and handling injection
 * of annotated fields.
 */
public final class HomeActivity$$InjectAdapter extends Binding<HomeActivity>
    implements Provider<HomeActivity>, MembersInjector<HomeActivity> {
  private Binding<com.squareup.otto.Bus> bus;

  public HomeActivity$$InjectAdapter() {
    super("com.aaron.smarttravel.main.HomeActivity", "members/com.aaron.smarttravel.main.HomeActivity", NOT_SINGLETON, HomeActivity.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    bus = (Binding<com.squareup.otto.Bus>) linker.requestBinding("com.squareup.otto.Bus", HomeActivity.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(bus);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<HomeActivity>}.
   */
  @Override
  public HomeActivity get() {
    HomeActivity result = new HomeActivity();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<HomeActivity>}.
   */
  @Override
  public void injectMembers(HomeActivity object) {
    object.bus = bus.get();
  }

}
