// Code generated by dagger-compiler.  Do not edit.
package com.aaron.smarttravel.main;

import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<SampleListFragmentLeft>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code SampleListFragmentLeft} and its
 * dependencies.
 *
 * Being a {@code Provider<SampleListFragmentLeft>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<SampleListFragmentLeft>} and handling injection
 * of annotated fields.
 */
public final class SampleListFragmentLeft$$InjectAdapter extends Binding<SampleListFragmentLeft>
    implements Provider<SampleListFragmentLeft>, MembersInjector<SampleListFragmentLeft> {
  private Binding<com.squareup.otto.Bus> bus;

  public SampleListFragmentLeft$$InjectAdapter() {
    super("com.aaron.smarttravel.main.SampleListFragmentLeft", "members/com.aaron.smarttravel.main.SampleListFragmentLeft", NOT_SINGLETON, SampleListFragmentLeft.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    bus = (Binding<com.squareup.otto.Bus>) linker.requestBinding("com.squareup.otto.Bus", SampleListFragmentLeft.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(bus);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<SampleListFragmentLeft>}.
   */
  @Override
  public SampleListFragmentLeft get() {
    SampleListFragmentLeft result = new SampleListFragmentLeft();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<SampleListFragmentLeft>}.
   */
  @Override
  public void injectMembers(SampleListFragmentLeft object) {
    object.bus = bus.get();
  }

}
