// Code generated by dagger-compiler.  Do not edit.
package com.aaron.smarttravel.injection;

import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<SmartTravelApplication>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code SmartTravelApplication} and its
 * dependencies.
 *
 * Being a {@code Provider<SmartTravelApplication>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<SmartTravelApplication>} and handling injection
 * of annotated fields.
 */
public final class SmartTravelApplication$$InjectAdapter extends Binding<SmartTravelApplication>
    implements Provider<SmartTravelApplication>, MembersInjector<SmartTravelApplication> {
  private Binding<com.squareup.otto.Bus> bus;
  private Binding<MultiDexApplication> supertype;

  public SmartTravelApplication$$InjectAdapter() {
    super("com.aaron.smarttravel.injection.SmartTravelApplication", "members/com.aaron.smarttravel.injection.SmartTravelApplication", NOT_SINGLETON, SmartTravelApplication.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    bus = (Binding<com.squareup.otto.Bus>) linker.requestBinding("com.squareup.otto.Bus", SmartTravelApplication.class, getClass().getClassLoader());
    supertype = (Binding<MultiDexApplication>) linker.requestBinding("members/com.aaron.smarttravel.injection.MultiDexApplication", SmartTravelApplication.class, getClass().getClassLoader(), false, true);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(bus);
    injectMembersBindings.add(supertype);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<SmartTravelApplication>}.
   */
  @Override
  public SmartTravelApplication get() {
    SmartTravelApplication result = new SmartTravelApplication();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<SmartTravelApplication>}.
   */
  @Override
  public void injectMembers(SmartTravelApplication object) {
    object.bus = bus.get();
    supertype.injectMembers(object);
  }

}
